// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WowRandomizer.Api.Database;

#nullable disable

namespace WowRandomizer.Api.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260302050449_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WowRandomizer.Api.Database.Entities.Faction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Factions");
                });

            modelBuilder.Entity("WowRandomizer.Api.Database.Entities.FactionRace", b =>
                {
                    b.Property<int>("FactionId")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.HasKey("FactionId", "RaceId");

                    b.HasIndex("RaceId");

                    b.ToTable("FactionRaces");
                });

            modelBuilder.Entity("WowRandomizer.Api.Database.Entities.GameClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("WowRandomizer.Api.Database.Entities.Profession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Professions");
                });

            modelBuilder.Entity("WowRandomizer.Api.Database.Entities.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsNeutral")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("WowRandomizer.Api.Database.Entities.RaceClass", b =>
                {
                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.HasKey("RaceId", "ClassId");

                    b.HasIndex("ClassId");

                    b.ToTable("RaceClasses");
                });

            modelBuilder.Entity("WowRandomizer.Api.Database.Entities.FactionRace", b =>
                {
                    b.HasOne("WowRandomizer.Api.Database.Entities.Faction", "Faction")
                        .WithMany("FactionRaces")
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WowRandomizer.Api.Database.Entities.Race", "Race")
                        .WithMany("FactionRaces")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faction");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("WowRandomizer.Api.Database.Entities.RaceClass", b =>
                {
                    b.HasOne("WowRandomizer.Api.Database.Entities.GameClass", "Class")
                        .WithMany("RaceClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WowRandomizer.Api.Database.Entities.Race", "Race")
                        .WithMany("RaceClasses")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("WowRandomizer.Api.Database.Entities.Faction", b =>
                {
                    b.Navigation("FactionRaces");
                });

            modelBuilder.Entity("WowRandomizer.Api.Database.Entities.GameClass", b =>
                {
                    b.Navigation("RaceClasses");
                });

            modelBuilder.Entity("WowRandomizer.Api.Database.Entities.Race", b =>
                {
                    b.Navigation("FactionRaces");

                    b.Navigation("RaceClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
